### ISSUE TITLE
glob is very broad, should be constrainted to the file format a bit more 

### ISSUE THREAD

**Issue by mallocz** [miraep8/Pomodoro_Viewer#5]
https://github.com/miraep8/Pomodoro_Viewer/blob/6406149db56d378b87bf6e908a84fc7fd9e02e36/folder_to_graph.py#L74

e.g. say is one has a `__pycache__` in the folder, then that would get picked up by the given glob pattern... Ideally it should handle `YYYY_MM_DD` or be closer to that.

**Comment by miraep8** [comment]
This is a good suggestion. The file format is now constrained to be of the form YYYY_MM_DD* Where Y/M/D are numbers between 0 and 9.  The * at the end is to accommodate different file endings.  Thanks for your suggestion!
