### ISSUE TITLE
Missing datapoint in generated HTML heatmap

### ISSUE THREAD

**Issue by mallocz** [miraep8/Pomodoro_Viewer#6]
I have the following data:
```
1  2022   Jan  13     Thu         2          200
```

That is outputted to the command line, but missed in the generated heatmap

For context here's the entire scrubbed dataset:
```
   Year Month Day Weekday  Week_Num  Num_Pomos
0  2022   Jan  11     Tue         2         51
1  2022   Jan  13     Thu         2         200
2  2022   Jan  19     Wed         3          400
3  2022   Jan  18     Tue         3          1000
4  2022   Jan  12     Wed         2          9000
5  2022   Jan  14     Fri         2          9001
```

Perhaps there's a bug in there?

Image (non-scrubbed)

<img width="240" alt="Screen Shot 2022-01-19 at 8 54 03 PM" src="https://user-images.githubusercontent.com/98066957/150247972-77f74787-2456-4a54-ad55-b3bbb2c7666e.png">

**Comment by miraep8** [comment]
Thank you for spotting this!  There was indeed a bug coming from the difference between Thurs/Thu.  This issue should be resolved in the latest version
